name: compile-catalog

on:
  workflow_dispatch: {}

jobs:
  data:
    runs-on: ubuntu-latest
    container: ghcr.io/opensanctions/graph-etl:main
    steps:
      - name: Compile the data catalog
        working-directory: /graph
        run: |
          python common/catalog.py
      # - name: Publish data to data.opensanctions.org
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #   run: |
      #     aws s3 cp --no-progress --cache-control "public, max-age=3600" --metadata-directive REPLACE --acl public-read catalog.json s3://data.opensanctions.org/graph/
      #     aws cloudfront create-invalidation --distribution-id ETROMAQBEJS91 --paths "/graph/catalog.json"
      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_UPLOAD_CREDENTIAL }}"
      - name: "Upload exported data to data.opensanctions.org"
        uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: /graph/catalog.json
          destination: data.opensanctions.org/graph/
