name: process-gb_coh_psc

on:
  schedule:
    - cron: "0 14 * * 1"
  workflow_dispatch: {}

jobs:
  data:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/opensanctions/graph-etl:main
      volumes:
        - /:/host
    defaults:
      run:
        working-directory: /graph/datasets/gb_coh_psc
    steps:
      - name: Maximize build space
        run: |
          rm -rf /host/usr/share/dotnet
          rm -rf /host/opt/ghc
          rm -rf "/host/usr/local/share/boost"
          rm -rf "/host/opt/hostedtoolcache"
          ls /host/opt
      - name: Parse and write the GB CoH PSC data
        run: |
          make process
      - name: Publish data to data.opensanctions.org
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          make publish
