name: process-gleif

on:
  schedule:
    - cron: "0 14 * * 1"
  workflow_dispatch: {}

jobs:
  data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Show ref
        run: |
          echo "$GITHUB_REF"
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get install -y -qq libicu-dev wget
          pip install -r requirements.txt
      - name: Parse and write the LEI data
        run: |
          make process
      - name: Publish data to data.opensanctions.org
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          make publish
