name: process-md_companies

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch: {}

jobs:
  data:
    runs-on: ubuntu-latest
    container: ghcr.io/opensanctions/graph-etl:main
    defaults:
      run:
        working-directory: /graph/datasets/md_companies
    steps:
      - name: Parse and write the register
        run: |
          make process
      - name: Publish data to data.opensanctions.org
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          make publish
