name: process-cz_business_register

on:
  schedule:
    - cron: "0 13 * * 1"
  workflow_dispatch: {}

jobs:
  data:
    runs-on: ubuntu-latest
    container: ghcr.io/opensanctions/graph-etl:main
    steps:
      - name: Parse and write the registry
        working-directory: /graph/datasets/cz_business_register
        run: |
          make process
      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_UPLOAD_CREDENTIAL }}"
      - name: "Upload exported data to data.opensanctions.org"
        uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: /graph/datasets/cz_business_register/data/export/
          destination: data.opensanctions.org/graph/cz_business_register
          parent: false
