name: process-dk_cvr

on:
  schedule:
    - cron: "0 14 * * 1"
  workflow_dispatch: {}

jobs:
  data:
    runs-on: ubuntu-latest
    container: ghcr.io/opensanctions/graph-etl:main
    # defaults:
    #   run:
    #     working-directory: /graph/datasets/dk_cvr
    steps:
      - uses: actions/checkout@v3.3.0
      - name: test call
        working-directory: /graph/datasets/dk_cvr
        run: |
          mkdir -p data/export
          touch data/export/test-file.md
      # - name: Parse and write the DK CVR data
      #   run: |
      #     make process
      # - name: Publish data to data.opensanctions.org
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #   run: |
      #     make publish
      - name: Publish data to data.opensanctions.org
        uses: ../workflows/actions/publish-export
        with:
          dataset: "dk_cvr"
